image: cypress/base:10

before_script:
    - npm install

test:
  stage: test
  script:
  - npm test

pages:
    stage: deploy
    script:
       - echo 'deploy'
    artifacts:
        paths:
            - mochawesome-report