image: cypress/base:10

before_script:
    - npm install

test:
    stage: test
    script:
        - npm test
    artifacts:
        paths:
            - mochawesome-report

pages:
    stage: deploy
    script:
        - mv mochawesome-report public
    artifacts:
        paths:
            - public
    rules:
        - when: always
