image: cypress/base:10

before_script:
    - npm install

test:
    stage: test
    script:
        - npm test

pages:
    stage: deploy
    script:
        - mkdir .public
        - cp -r ./mochawesome-report .public
        - mv .public public
    artifacts:
        paths:
            - public
    rules:
        - when: always
