name: run_tests

on:
  # executa esse workflow sempre que subir uma alteracao para a branch master
  push:
    branches: [ main ]

jobs:
  build:
    # maquina onde o workflow será executado
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # vai executar 2x o mesmo workflow (paralelo) para cada node-version        
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cypress run
      uses: cypress-io/github-action@v2
      id: cypress
      continue-on-error: true
      with:
        browser: chrome

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: mochawesome-report
