name: run_tests

on:
  # executa esse workflow sempre que subir uma alteracao para a branch master
  push:
    branches: [ main ]

jobs:
  test:
    # maquina onde o workflow será executado
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cypress run
      uses: cypress-io/github-action@v2
      continue-on-error: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mochawesome-report
